// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA83W-MNdSa3_bqT4wQXyjuoXw8po-WWlI',
    appId: '1:71670415294:web:3999e4bbb48ad2678583ef',
    messagingSenderId: '71670415294',
    projectId: 'dental-clinic-app-1032a',
    authDomain: 'dental-clinic-app-1032a.firebaseapp.com',
    storageBucket: 'dental-clinic-app-1032a.appspot.com',
    measurementId: 'G-DYC258VQSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLifEM7-IL16uDVbWVSTMA-pqcb66IC8',
    appId: '1:71670415294:android:66c08cc5b91e3ed58583ef',
    messagingSenderId: '71670415294',
    projectId: 'dental-clinic-app-1032a',
    storageBucket: 'dental-clinic-app-1032a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBor7747ZSKSdm8shruJf63m1FtFtvbomQ',
    appId: '1:71670415294:ios:97a711678d34f2358583ef',
    messagingSenderId: '71670415294',
    projectId: 'dental-clinic-app-1032a',
    storageBucket: 'dental-clinic-app-1032a.appspot.com',
    iosBundleId: 'com.eraasoft.dentalClinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBor7747ZSKSdm8shruJf63m1FtFtvbomQ',
    appId: '1:71670415294:ios:b8d4485bc0ffd6f08583ef',
    messagingSenderId: '71670415294',
    projectId: 'dental-clinic-app-1032a',
    storageBucket: 'dental-clinic-app-1032a.appspot.com',
    iosBundleId: 'com.eraasoft.dentalClinicApp.RunnerTests',
  );
}
